"""Page 4 — AI Investigator"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import streamlit as st

from dashboard.api_client import get_alerts, get_investigations, generate_investigation, get_config
from dashboard.styles import apply_global_styles, section_header, severity_badge, status_badge, info_banner

st.set_page_config(page_title="AI Investigator — SentinelAI", page_icon="🤖", layout="wide")
apply_global_styles()

if "token" not in st.session_state:
    st.warning("Please sign in from the Home page.")
    st.stop()

role = st.session_state.get("role", "viewer")
section_header("🤖 AI Investigator", "Evidence-based incident investigation")

# AI status
config = get_config()
if config:
    ai_provider = config.get("ai_provider", "none")
    ai_configured = config.get("ai_configured", False)
    if ai_configured:
        info_banner(f"✅ AI Provider: <strong>{ai_provider}</strong> — LLM-powered investigation active", "success")
    else:
        info_banner(
            "ℹ️ AI Provider: <strong>Local Fallback</strong> — "
            "Structured evidence-based summaries (no external API required). "
            "Set AI_PROVIDER + AI_API_KEY in .env to enable LLM mode.",
            "info",
        )

st.markdown("""
<div style="background:#1a2035;padding:12px 16px;border-radius:8px;border:1px solid #1e3050;margin:8px 0">
⚠️ <strong>Important:</strong> AI-generated summaries distinguish observed facts from AI hypotheses.
They do NOT replace human investigation. All recommendations require human review.
The AI cannot invent event IDs, IP addresses, or evidence not present in the database.
</div>
""", unsafe_allow_html=True)

# --- Alert selector ---
alerts = get_alerts(limit=100)
if not alerts:
    st.info("No alerts found. Load demo data and run detection first.")
    st.stop()

alert_options = {
    f"{a['rule_name']} | {a['severity'].upper()} | {a['created_at'][:10]} | ID:{a['id'][:8]}": a["id"]
    for a in alerts
}

selected_label = st.selectbox("Select Alert to Investigate", list(alert_options.keys()))
selected_alert_id = alert_options.get(selected_label)

if not selected_alert_id:
    st.stop()

# Show alert summary
selected_alert = next((a for a in alerts if a["id"] == selected_alert_id), None)
if selected_alert:
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown(f"**Severity:** ", unsafe_allow_html=False)
        st.markdown(severity_badge(selected_alert.get("severity", "")), unsafe_allow_html=True)
    with col2:
        st.markdown(f"**Status:**")
        st.markdown(status_badge(selected_alert.get("status", "")), unsafe_allow_html=True)
    with col3:
        st.markdown(f"**Risk Score:** {selected_alert.get('risk_score', 0):.0f} / 100")

    st.markdown(f"**Source IP:** {selected_alert.get('source_ip', 'N/A')} | **Username:** {selected_alert.get('username', 'N/A')}")

st.markdown("---")

# --- Generate or view investigation ---
col_gen, col_hist = st.columns([1, 1])

with col_gen:
    if role in ("admin", "analyst"):
        if st.button("🤖 Generate Investigation Summary", use_container_width=True, key="gen_investigation"):
            with st.spinner("Generating investigation summary..."):
                result = generate_investigation(selected_alert_id)
            if result:
                st.success(f"Generated by: **{result.get('generated_by', 'unknown')}**")
                st.session_state["latest_investigation"] = result
                st.rerun()
    else:
        st.info("Analyst or Admin role required to generate investigations.")

with col_hist:
    past = get_investigations(selected_alert_id)
    if past:
        st.markdown(f"**{len(past)} previous investigation(s) on record**")

# --- Display latest investigation ---
if "latest_investigation" in st.session_state:
    inv = st.session_state["latest_investigation"]
    st.markdown("---")
    st.markdown(f"#### 📋 Investigation Summary")
    st.markdown(
        f'<div style="background:#0d1628;border:1px solid #1e3050;border-radius:8px;padding:4px 0">'
        f'<div style="background:#1a2035;padding:8px 16px;border-radius:8px 8px 0 0;color:#8892a4;font-size:0.85em">'
        f'Generated by: <strong style="color:#00d4ff">{inv.get("generated_by","unknown")}</strong>'
        f'</div></div>',
        unsafe_allow_html=True,
    )
    st.markdown(inv.get("summary", "No summary available."))
elif past := get_investigations(selected_alert_id):
    st.markdown("---")
    st.markdown("#### 📋 Most Recent Investigation")
    latest = past[0]
    st.markdown(f'<span style="color:#8892a4;font-size:0.85em">Generated by: <strong style="color:#00d4ff">{latest["generated_by"]}</strong> | {latest["created_at"][:19]}</span>', unsafe_allow_html=True)
    st.markdown(latest.get("summary", ""))
else:
    if role in ("admin", "analyst"):
        st.info("No investigation summaries yet. Click 'Generate Investigation Summary' above.")
    else:
        st.info("No investigation summaries available for this alert.")
